apiVersion: v1
kind: PersistentVolume
metadata:
  name: chandana-pv-retail
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    path: /var/nfs/general/retail
    server: 13.232.123.117
