apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-sc
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.8.33
  share: /exported/path
reclaimPolicy: Delete
volumeBindingMode: Immediate
 


